#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE DATABASE llama_vector;
    CREATE USER admin WITH ENCRYPTED PASSWORD '123456';
    GRANT ALL PRIVILEGES ON DATABASE llama_vector TO admin;
    \c llama_vector;
    GRANT ALL ON SCHEMA public TO admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO admin;
    CREATE EXTENSION IF NOT EXISTS "vector";
EOSQL